### PR TITLE
wobbly: Remove paint box override hack

### PR DESCRIPTION
**Pull request by smspillaz**
Now that clutter correctly computes the paint volume during
effects as the paint volume *up to* the current effect, there's
no need to override the get_paint_volume vfunc and lie about
the paint box.

https://phabricator.endlessm.com/T23692

### CODE REVIEW

**Comment by smspillaz** [comment]
> I have a question though: if this removes a change we introduced, should revert that patch instead? 

In this case, the relevant "change" was introduced when we merged in the Wobbly Windows branch to the shell a few years ago in 1e38f :)

**Comment by joaquimrocha** [comment]
> In this case, the relevant "change" was introduced when we merged in the Wobbly Windows branch to the shell a few years ago in 1e38f :)

Okay, I still feel maybe this should be squashed on a rebase, but the changes are approved, so feel free to merge (after solving the current conflicts).

**Comment by GeorgesStavracas** [comment]
@smspillaz I agree that it would be better to rename the title of the commit as `fixup! <title of the commit that introduced it>`. Keep the commit message though, it'll help a lot at the next rebase.

**Comment by smspillaz** [comment]
> I agree that it would be better to rename the title of the commit as fixup! <title of the commit that introduced it>

Hmm, it would be tricky to do that, I suppose, since the relevant libwobbly API changed a little bit in the meantime and (and the file changed from C++ to C). I think it'd make sense on the next rebase to just squash all the wobbly stuff together.

**Pull request merged**
